### ISSUE TITLE
Shouldn't the icon content be applied to ::before?

### ISSUE THREAD

**Issue by andreptb** [jedfoster/fontastic2sass#1]
@jedfoster ,

Nice work! 

When generating the placeholder classes:

https://github.com/jedfoster/fontastic2sass/blob/a218e1cd577817288b3df4e5a638f37548a15f71/lib/fontastic2sass/templates/list.sass.erb#L25

Wouldn't be more convenient for the pseudo-class to apply `$value` to `::before` selector? Something like:

```css
@each $value in $content {
  &:before {
    content: $value;
  }
}
```

Without this, the example you provided below doesn't work:

https://github.com/jedfoster/fontastic2sass/blob/a218e1cd577817288b3df4e5a638f37548a15f71/lib/fontastic2sass/templates/map.sass.erb#L16
